version: '3'
services:
  app:
    image: golang:1.14
    container_name: agility
    volumes:
    - ./:/app
    - ./cache/mod:/go/pkg/mod
    - ./cache/go-build:/root/.cache/go-build
    - ./ui/dist:/usr/share/agility/assets
    working_dir: /app
    ports:
    - "8080:80"
    command: [go, run, .]
    env_file:
    - dev.env
  webpack:
    image: node:12
    container_name: agility_webpack
    volumes:
    - ./ui:/build
    working_dir: /build
    command: [npm, run, watch]
